### ISSUE TITLE
Altium Folder Mash

### ISSUE THREAD

**Issue by Daneca** [Semi-ATE/Project-Template#11]
Hi Tom,

I would like to clear and arrange a bit the folder for the Altium Project Template.
There are a lot of files and folders which are not for this location/repo.

Also I would like to edit some things to the gitignore as currently the History and the __Preview are still pushed to the server.
I have checked how we are doing them currently and the text is as follows "  **/__Previews* and **/History*  ".
Please let me know in slack when you have half an hour tomorrow.

Thanks in advance!

Best regards,
Daniel

**Comment by nerohmot** [comment]
so the __Previews and History things we fixed together, please go ahead and arrange the folder structure nicely :-)
