### ISSUE TITLE
Manufacturer Partnumber shown on Schematic

### ISSUE THREAD

**Issue by martin-mm** [Semi-ATE/Project-Template#7]
The Manufacturer Partnumber should not be shown in the Schematics, instead the Value should be shown. The Manufacturer Partnumber contains information like reel size, packaging, etc which shall not be shown in the Schematics.

**Comment by Daneca** [comment]
I see what you mean. For the final library I understand your point but what is expected to be updated in the current SCT8 library?

**Comment by Daneca** [comment]
Release of the offical libraries is in place and issue is resolved as commented on the 31.05.2021.
