### ISSUE TITLE
Solder Mask Expansion in PCB Libraries and Paste Mask

### ISSUE THREAD

**Issue by martin-mm** [Semi-ATE/Project-Template#8]
Solder Mask Expansion in PCB Libraries is from rules but should be set manually to 50um, Paste Mask should be set manually to 0

**Comment by Daneca** [comment]
OK, It is clear for the Semi-ATE library but should this be updated for the SCT8 library also?

**Comment by Daneca** [comment]
Completed in upcoming official Semi-ATE.PcbLib (standard footprint library)
